#!/usr/bin/env python3
"""Render an executed notebook as a documentation page.

    scripts/validate-notebooks.sh airline_analysis        # (optional) check it still runs
    scripts/render-notebook-page.py notebooks/airline_analysis.ipynb docs/notebook.md

The committed notebooks carry no stored outputs — they would bloat the repository and
leak whatever paths the machine that ran them happened to have. That is right for the
repository and wrong for the documentation site, where someone who has not cloned
anything still needs to see what the tools actually say.

So the page is generated from a real execution: this script runs the notebook (or reads
one already executed with ``--from``) and writes markdown that interleaves the prose, the
code and the output. Nothing in the result is illustrative.
"""

import argparse
import glob
import json
import os
import re
import subprocess
import sys
import tempfile

# Spark's progress bars are carriage-return animations; on a page they are noise.
PROGRESS = re.compile(r"\[Stage \d+:[^\r\n]*[\r\n]?")
ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")

# Lines a reader does not need: JVM warnings, log4j notices, and the like.
NOISE = re.compile(
    r"^(WARNING: |Using Spark's default log4j|Setting default log level|"
    r"To adjust logging level|\d{2}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} (WARN|INFO) )")


def clean(text):
    """Strip progress animations, ANSI colour and log noise from cell output."""
    text = ANSI.sub("", PROGRESS.sub("", text))
    # A carriage return means "overwrite this line": what a terminal would show is only
    # what follows the last one. Keeping the whole line instead leaves the swept-out
    # remains of Spark's progress bar as a long run of spaces in front of real output.
    text = "\n".join(line.split("\r")[-1] for line in text.split("\n"))
    kept = [line.rstrip() for line in text.split("\n") if not NOISE.match(line)]
    while kept and not kept[0].strip():
        kept.pop(0)
    while kept and not kept[-1].strip():
        kept.pop()
    return "\n".join(kept)


def outputs_of(cell):
    """Everything a cell printed, as one string."""
    parts = []
    for output in cell.get("outputs", []):
        if "text" in output:
            parts.append("".join(output["text"]))
        elif output.get("output_type") == "execute_result":
            parts.append("".join(output.get("data", {}).get("text/plain", [])))
        elif output.get("output_type") == "error":
            parts.append("\n".join(output.get("traceback", [])))
    return clean("".join(parts))


# The notebook prints where it connected. That line is how the page knows what to
# claim, rather than repeating whatever the last editor believed.
MASTER = re.compile(r"^Spark \S+ - (\S+)", re.M)


def where_it_ran(notebook):
    """The Spark master the executed notebook actually connected to, if it said."""
    for cell in notebook["cells"]:
        if cell["cell_type"] != "code":
            continue
        found = MASTER.search(outputs_of(cell))
        if found:
            return found.group(1)
    return None


def banner(source_path, master):
    """The note at the top of the page: what this is, and what produced it.

    Written here rather than in the page, because it makes a claim about how the numbers
    below were produced and a hand-written claim drifts from the truth the moment
    someone regenerates the page somewhere else.
    """
    name = os.path.basename(source_path)
    link = ("https://github.com/BigAsterisk/BigAsterisk/blob/main/notebooks/" + name)
    if master and master.startswith("spark://"):
        against = "against a real Spark cluster — a standalone master with workers in " \
                  "their own containers"
    elif master:
        against = f"against a local Spark (`{master}`)"
    else:
        against = "against Spark"
    return [
        '!!! abstract "This is a notebook, executed"',
        "",
        "    Everything below — every number, every ranking — came out of running",
        f"    [`notebooks/{name}`]({link})",
        f"    {against}. Nothing is an example of what you might see.",
        "    Setup is at the bottom; it takes one command.",
        "",
    ]


def render(notebook, source_path, executed_on):
    lines = [
        "<!-- Generated by scripts/render-notebook-page.py — do not edit by hand. -->",
        "",
    ] + banner(source_path, where_it_ran(notebook))

    for cell in notebook["cells"]:
        source = "".join(cell["source"]).rstrip()
        if not source.strip():
            continue

        if cell["cell_type"] == "markdown":
            lines += [source, ""]
            continue

        # The bootstrap cell is machinery, not narrative: it finds jars and sets paths.
        if "BIGASTERISK_HOME" in source and "SPARK_JARS" in source:
            continue

        lines += ["```python", source, "```", ""]
        printed = outputs_of(cell)
        if printed:
            lines += ["```text", printed, "```", ""]

    lines += [
        "---",
        "",
        "## Run it yourself",
        "",
        "```bash",
        "scripts/cluster.sh up 3     # master, workers, history server, JupyterLab",
        "```",
        "",
        "Then open <http://localhost:8888> and pick "
        f"`{os.path.basename(source_path)}`. Watch <http://localhost:8080> while it runs "
        "to see the work land on the workers.",
        "",
        "Without a cluster, `scripts/validate-notebooks.sh "
        f"{os.path.basename(source_path).replace('.ipynb', '')}` executes it headlessly, "
        "and [Setup](setup.md) covers the other ways in.",
        "",
        f"*This page was generated from a real run on {executed_on}. To regenerate it:*",
        "",
        "```bash",
        f"scripts/render-notebook-page.py {source_path} docs/notebook.md",
        "```",
    ]
    return "\n".join(lines) + "\n"


def toolchain(root):
    """The environment a notebook needs, discovered the way the validator discovers it.

    Not inherited from the shell: a run whose `PYTHONPATH` happens to be unset fails
    inside nbconvert with `No module named pyspark`, three layers down, after however
    long the earlier cells took. Better to set it here and be sure the page is generated
    against the Spark the jars were built for.
    """
    environment = dict(os.environ)
    environment.setdefault("BIGASTERISK_HOME", root)

    # The project's own JDK wins over whatever the shell has: PySpark 4.1 needs 17+,
    # and an older JAVA_HOME fails deep inside the gateway with a bare JNI error.
    jdks = sorted(glob.glob(os.path.join(root, "tools", "jdk-17*")))
    if jdks:
        home = os.path.join(jdks[0], "Contents", "Home")
        environment["JAVA_HOME"] = home if os.path.isdir(home) else jdks[0]

    spark = environment.get("SPARK_HOME") or next(
        iter(sorted(glob.glob(os.path.join(root, "tools", "spark-*-bin-hadoop*")))), None)
    if not spark:
        raise SystemExit("No Spark distribution in tools/. Run bin/bootstrap, "
                         "or set SPARK_HOME.")
    environment["SPARK_HOME"] = spark

    interpreter = os.path.join(root, "tools", "python", "bin", "python3")
    if not os.access(interpreter, os.X_OK):
        interpreter = sys.executable
    environment["PYSPARK_PYTHON"] = interpreter

    # py4j is found rather than named: its version travels with the distribution.
    py4j = sorted(glob.glob(os.path.join(spark, "python", "lib", "py4j-*-src.zip")))
    environment["PYTHONPATH"] = os.pathsep.join(
        [os.path.join(spark, "python")] + py4j[:1] + [os.path.join(root, "python")])
    return environment


def execute(path):
    """Run the notebook and return it with its outputs."""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    environment = toolchain(root)

    with tempfile.NamedTemporaryFile(suffix=".ipynb", delete=False) as out:
        target = out.name
    try:
        subprocess.run(
            [sys.executable, "-m", "nbconvert", "--to", "notebook", "--execute",
             "--ExecutePreprocessor.timeout=1800", "--output", target, path],
            check=True, env=environment)
        with open(target) as handle:
            return json.load(handle)
    finally:
        if os.path.exists(target):
            os.unlink(target)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("notebook", help="the .ipynb to render")
    parser.add_argument("page", help="the markdown file to write")
    parser.add_argument("--from", dest="executed", default=None,
                        help="an already-executed notebook, instead of running it again")
    parser.add_argument("--date", default=None, help="the run date to record on the page")
    args = parser.parse_args()

    if args.executed:
        with open(args.executed) as handle:
            notebook = json.load(handle)
    else:
        notebook = execute(args.notebook)

    missing = [i for i, c in enumerate(notebook["cells"])
               if c["cell_type"] == "code" and c["source"] and not c.get("outputs")]
    if len(missing) > 3:
        print(f"warning: {len(missing)} code cells have no output — "
              f"was the notebook executed?", file=sys.stderr)

    date = args.date or __import__("datetime").date.today().isoformat()
    with open(args.page, "w") as handle:
        handle.write(render(notebook, args.notebook, date))
    print(f"wrote {args.page} from {len(notebook['cells'])} cells")


if __name__ == "__main__":
    main()
