#!/usr/bin/env python3
"""Render an executed notebook as a documentation page.

    scripts/validate-notebooks.sh airline_analysis        # (optional) check it still runs
    scripts/render-notebook-page.py notebooks/airline_analysis.ipynb docs/notebook.md

The committed notebooks carry no stored outputs — they would bloat the repository and
leak whatever paths the machine that ran them happened to have. That is right for the
repository and wrong for the documentation site, where someone who has not cloned
anything still needs to see what the tools actually say.

So the page is generated from a real execution: this script runs the notebook (or reads
one already executed with ``--from``) and writes markdown that interleaves the prose, the
code and the output. Nothing in the result is illustrative.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile

# Spark's progress bars are carriage-return animations; on a page they are noise.
PROGRESS = re.compile(r"\[Stage \d+:[^\r\n]*[\r\n]?")
ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")

# Lines a reader does not need: JVM warnings, log4j notices, and the like.
NOISE = re.compile(
    r"^(WARNING: |Using Spark's default log4j|Setting default log level|"
    r"To adjust logging level|\d{2}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} (WARN|INFO) )")


def clean(text):
    """Strip progress animations, ANSI colour and log noise from cell output."""
    text = ANSI.sub("", PROGRESS.sub("", text))
    kept = [line for line in text.split("\n") if not NOISE.match(line)]
    while kept and not kept[0].strip():
        kept.pop(0)
    while kept and not kept[-1].strip():
        kept.pop()
    return "\n".join(kept)


def outputs_of(cell):
    """Everything a cell printed, as one string."""
    parts = []
    for output in cell.get("outputs", []):
        if "text" in output:
            parts.append("".join(output["text"]))
        elif output.get("output_type") == "execute_result":
            parts.append("".join(output.get("data", {}).get("text/plain", [])))
        elif output.get("output_type") == "error":
            parts.append("\n".join(output.get("traceback", [])))
    return clean("".join(parts))


def render(notebook, source_path, executed_on):
    lines = [
        "<!-- Generated by scripts/render-notebook-page.py — do not edit by hand. -->",
        "",
    ]

    for cell in notebook["cells"]:
        source = "".join(cell["source"]).rstrip()
        if not source.strip():
            continue

        if cell["cell_type"] == "markdown":
            lines += [source, ""]
            continue

        # The bootstrap cell is machinery, not narrative: it finds jars and sets paths.
        if "BIGASTERISK_HOME" in source and "SPARK_JARS" in source:
            continue

        lines += ["```python", source, "```", ""]
        printed = outputs_of(cell)
        if printed:
            lines += ["```text", printed, "```", ""]

    lines += [
        "---",
        "",
        "## Run it yourself",
        "",
        "```bash",
        "scripts/cluster.sh up 3     # master, workers, history server, JupyterLab",
        "```",
        "",
        "Then open <http://localhost:8888> and pick "
        f"`{os.path.basename(source_path)}`. Watch <http://localhost:8080> while it runs "
        "to see the work land on the workers.",
        "",
        "Without a cluster, `scripts/validate-notebooks.sh "
        f"{os.path.basename(source_path).replace('.ipynb', '')}` executes it headlessly, "
        "and [Setup](setup.md) covers the other ways in.",
        "",
        f"*This page was generated from a real run on {executed_on}. To regenerate it:*",
        "",
        "```bash",
        f"scripts/render-notebook-page.py {source_path} docs/notebook.md",
        "```",
    ]
    return "\n".join(lines) + "\n"


def execute(path):
    """Run the notebook and return it with its outputs."""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    environment = dict(os.environ)
    environment.setdefault("BIGASTERISK_HOME", root)

    with tempfile.NamedTemporaryFile(suffix=".ipynb", delete=False) as out:
        target = out.name
    try:
        subprocess.run(
            [sys.executable, "-m", "nbconvert", "--to", "notebook", "--execute",
             "--ExecutePreprocessor.timeout=1800", "--output", target, path],
            check=True, env=environment)
        with open(target) as handle:
            return json.load(handle)
    finally:
        if os.path.exists(target):
            os.unlink(target)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("notebook", help="the .ipynb to render")
    parser.add_argument("page", help="the markdown file to write")
    parser.add_argument("--from", dest="executed", default=None,
                        help="an already-executed notebook, instead of running it again")
    parser.add_argument("--date", default=None, help="the run date to record on the page")
    args = parser.parse_args()

    if args.executed:
        with open(args.executed) as handle:
            notebook = json.load(handle)
    else:
        notebook = execute(args.notebook)

    missing = [i for i, c in enumerate(notebook["cells"])
               if c["cell_type"] == "code" and c["source"] and not c.get("outputs")]
    if len(missing) > 3:
        print(f"warning: {len(missing)} code cells have no output — "
              f"was the notebook executed?", file=sys.stderr)

    date = args.date or __import__("datetime").date.today().isoformat()
    with open(args.page, "w") as handle:
        handle.write(render(notebook, args.notebook, date))
    print(f"wrote {args.page} from {len(notebook['cells'])} cells")


if __name__ == "__main__":
    main()
